feature(OSS-663): notify users about new version
fauna/faunadb-python pull request #190
Opened 2021-06-01 09:32 UTC by fireridlle

[Notify users via command line when driver has been updated](https://faunadb.atlassian.net/browse/OSS-663)

https://faunadb.atlassian.net/browse/OSS-663

2021-06-01 13:52 UTC, parkhomenko commented on faunadb/__init__.py
> +  if latest_version_arr[i] > current_version[i]:
I understand that this situation is not really possible, but what if `current_version` is 5.0.0 and `latest_version` is 4.2.0. I think the `is_new_version_available` returns true.

2021-06-01 13:54 UTC, parkhomenko commented on faunadb/__init__.py
> +if True: #is_new_version_available:
Do you need to return the commented version?

2021-06-01 13:57 UTC, parkhomenko requested changes
Can we put the code starting from line 12 and add 1 or 2 unit tests?
I mean you can create a function that accepts 2 params: current_version and latest_version and returns the message that needs to be rendered in case the latest_version is newer than the currently installed.

2021-06-03 08:34 UTC, parkhomenko approved these changes

2021-06-03 08:54 UTC, vadimLF approved these changes
LGTM

2021-06-04 12:44 UTC, merged