release: Bumped to version 5.0.0
fauna/faunadb-python pull request #207
Opened 2021-10-29 15:26 UTC by parkhomenko

Bumped to 5.0.0

2021-11-02 16:41 UTC, faunaee requested changes
The README.md file does not describe what the driver exception hierarchy is, or what it means for developers.

2021-11-02 17:53 UTC, faunaee requested changes
A few suggestions to improve the language in the exceptions coverage.

2021-11-02 17:53 UTC, faunaee commented on README.rst
> +for example:
```suggestion
With the 5.0.0 release, child classes of the base HttpError class now exist.
For example:

```

2021-11-02 17:53 UTC, faunaee commented on README.rst
> +    pass
Including `pass` here (and in subsequent examples) seems inappropriate. Perhaps just list the exception types and a brief description for each?

2021-11-02 17:53 UTC, faunaee commented on README.rst
> +where each class corresponds to the error code from fauna database server,
```suggestion
Each class corresponds to an error code from Fauna.
```

2021-11-02 17:53 UTC, faunaee commented on README.rst
> +you can inspect "errors.py" file for more information on how it is implemented.
```suggestion
Inspect the [`errors.py`](https://github.com/fauna/faunadb-python/blob/v5/faunadb/errors.py)
file for more information on how it is implemented.
```

2021-11-02 17:53 UTC, faunaee commented on README.rst
> +Below you can see an example of how you can take advantage of a new exception hierarchy:
```suggestion
The following example demonstrates the methods that you can access from the exception object:
```

2021-11-17 15:55 UTC, parkhomenko commented
Opened a new one:
https://github.com/fauna/faunadb-python/pull/213

2021-11-17 15:55 UTC, closed without merging